<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wireguard.proto

namespace Vpn\GPBMetadata;

class Wireguard
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
�

wireguard.protoproto.wireguard"�
MountRequest
interface_name (	
private_key (	
listen_port (	
physical_interface (	
subnet (	
address (	
mtu (	"
EmptyRequest"*
InterfaceRequest
interface_name (	"�
AddPeerRequest
user_id (	
device_name (	
interface_name (	

public_key (	

preshared_key (	
allowed_ips (	
persistent_keepalive (	
endpoint (	"?
DeletePeerRequest
interface_name (	

public_key (	""
MessageResponse
message (	"%
NetworkInterface
	interface (	"I
ListInterfacesResponse/
data (2!.proto.wireguard.NetworkInterface2�
WireguardServiceH
mount.proto.wireguard.MountRequest .proto.wireguard.MessageResponseM
umount!.proto.wireguard.InterfaceRequest .proto.wireguard.MessageResponseK
down!.proto.wireguard.InterfaceRequest .proto.wireguard.MessageResponseI
up!.proto.wireguard.InterfaceRequest .proto.wireguard.MessageResponseN
restart!.proto.wireguard.InterfaceRequest .proto.wireguard.MessageResponseL
addPeer.proto.wireguard.AddPeerRequest .proto.wireguard.MessageResponseR

deletePeer".proto.wireguard.DeletePeerRequest .proto.wireguard.MessageResponseT

interfaces.proto.wireguard.EmptyRequest\'.proto.wireguard.ListInterfacesResponsebproto3'
        , true);

        static::$is_initialized = true;
    }
}

