<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wireguard.proto

namespace VPN\Proto\Wireguard;

use Vpn\Vendor\Google\Protobuf\Internal\GPBType;
use Vpn\Vendor\Google\Protobuf\Internal\RepeatedField;
use Vpn\Vendor\Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>proto.wireguard.EmptyRequest</code>
 */
class EmptyRequest extends \Vpn\Vendor\Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Vpn\GPBMetadata\Wireguard::initOnce();
        parent::__construct($data);
    }

}

